language: python
dist: bionic
notifications:
  irc:
    channels:
    - chat.freenode.net#kcli
    on_success: change
    on_failure: always
sudo: required
python:
- 3.6
virtualenv:
  system_site_packages: true

before_install:
- pip3 install pep8 twine misspellings stdeb requests
- pip3 install setuptools --upgrade


script:
    # source analysis|linting
    - ${PWD}/tests/pipeline/stages/linting.sh
    # build 
    - ${PWD}/tests/pipeline/stages/build.sh
after_success:
    # release 
    - ${PWD}/tests/pipeline/stages/release.sh
